
name: mirror check
on:
  push:
    branches: [github-integration]
    paths:
      - "docs/mirrors/**.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.1"
      - name: install
        run: go install github.com/myml/mirrors@v0.0.2
      - name: package_zh
        run: mirrors -packages_path docs/mirrors/packages_zh.md  > docs/mirrors/packages_zh_mark.css
      - name: package_en
        run: mirrors -packages_path docs/mirrors/packages_en.md  > docs/mirrors/packages_en_mark.css
      - name: release_zh
        run: mirrors -releases_path docs/mirrors/releases_zh.md  > docs/mirrors/releases_zh_mark.css
      - name: release_en
        run: mirrors -releases_path docs/mirrors/releases_en.md  > docs/mirrors/releases_en_mark.css
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "auto: Mirrors mark"
          commit_user_name: myml
          commit_user_email: wurongjie1@gmail.com
